const testHistory = [
	{
		light: "e4",
		dark: "e6",
	},
	{
		light: "Qg4",
		dark: "Qh4",
	},
	{
		light: "Qxg7",
		dark: "Qxh2",
	},
	{
		light: "Qxh7",
		dark: "Qxh1",
	},
	{
		light: "Qxh8",
		dark: "Qxg2",
	},
	{
		light: "Qxg8",
		dark: "Qxg1",
	},
	{
		light: "Qxf7+",
		dark: "Kd8",
	},
	{
		light: "Qxe6",
		dark: "Qxf2+",
	},
	{
		light: "Kd1",
		dark: "Qf4",
	},
	{
		light: "Qb6",
		dark: "Qxe4",
	},
	{
		light: "Qxa7",
		dark: "Qxc2+",
	},
	{
		light: "Ke1",
		dark: "Qxb2",
	},
	{
		light: "Qxa8",
		dark: "Qxa2",
	},
	{
		light: "Qxb8",
		dark: "Qxa1",
	},
	{
		light: "Qxb7",
		dark: "Qxb1",
	},
	{
		light: "Qxc8+",
		dark: "Ke7",
	},
	{
		light: "Qxf8+",
		dark: "Ke6",
	},
	{
		light: "Qf5+",
		dark: "Ke7",
	},
	{
		light: "d3",
		dark: "Qxd3",
	},
	{
		light: "Qd5",
		dark: "Qxf1+",
	},
	{
		light: "Kd2",
		dark: "Kd8",
	},
	{
		light: "Ke3",
		dark: "Qxc1+",
	},
	{
		light: "Kf2",
		dark: "Qh6",
	},
	{
		light: "Qf7",
		dark: "Kc8",
	},
	{
		light: "Qe7",
		dark: "Kb8",
	},
	{
		light: "Qxd7",
		dark: "Ka8",
	},
	{
		light: "Kg2",
		dark: "c5",
	},
	{
		light: "Qc7",
		dark: "Qb6",
	},
	{
		light: "Qxb6",
		dark: "c4",
	},
	{
		light: "Qc7",
		dark: "c3",
	},
	{
		light: "Kh1",
		dark: "c2",
	},
	{
		light: "Qb6",
	},
];

const testPieces = [
	{
		name: "darkKing",
		type: "king",
		position: {
			x: 0,
			y: 0,
		},
		color: "dark",
		image: "kd.png",
		movements: [],
		hasMoved: true,
	},
	{
		name: "darkPawn3",
		type: "pawn",
		position: {
			x: 2,
			y: 6,
		},
		color: "dark",
		image: "pd.png",
		movements: [],
		hasMoved: true,
	},
	{
		name: "lightQueen",
		type: "queen",
		position: {
			x: 1,
			y: 2,
		},
		color: "light",
		image: "ql.png",
		movements: [],
		hasMoved: true,
	},
	{
		name: "lightKing",
		type: "king",
		position: {
			x: 7,
			y: 7,
		},
		color: "light",
		image: "kl.png",
		movements: [],
		hasMoved: true,
	},
];

const defineInitialPositions = (numbers) => {
	const darkOnTop = numbers[0] === "8";

	const darkPieces = [
		{
			name: "darkRook1",
			type: "rook",
			position: darkOnTop ? { x: 0, y: 0 } : { x: 0, y: 7 },
			color: "dark",
			image: "rd.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "darkKnight1",
			type: "knight",
			position: darkOnTop ? { x: 1, y: 0 } : { x: 1, y: 7 },
			color: "dark",
			image: "nd.png",
			movements: [],
		},
		{
			name: "darkBishop1",
			type: "bishop",
			position: darkOnTop ? { x: 2, y: 0 } : { x: 2, y: 7 },
			color: "dark",
			image: "bd.png",
			movements: [],
		},
		{
			name: "darkQueen",
			type: "queen",
			position: darkOnTop ? { x: 3, y: 0 } : { x: 4, y: 7 },
			color: "dark",
			image: "qd.png",
			movements: [],
		},
		{
			name: "darkKing",
			type: "king",
			position: darkOnTop ? { x: 4, y: 0 } : { x: 3, y: 7 },
			color: "dark",
			image: "kd.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "darkBishop2",
			type: "bishop",
			position: darkOnTop ? { x: 5, y: 0 } : { x: 5, y: 7 },
			color: "dark",
			image: "bd.png",
			movements: [],
		},
		{
			name: "darkKnight2",
			type: "knight",
			position: darkOnTop ? { x: 6, y: 0 } : { x: 6, y: 7 },
			color: "dark",
			image: "nd.png",
			movements: [],
		},
		{
			name: "darkRook2",
			type: "rook",
			position: darkOnTop ? { x: 7, y: 0 } : { x: 7, y: 7 },
			color: "dark",
			image: "rd.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "darkPawn1",
			type: "pawn",
			position: darkOnTop ? { x: 0, y: 1 } : { x: 0, y: 6 },
			color: "dark",
			image: "pd.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "darkPawn2",
			type: "pawn",
			position: darkOnTop ? { x: 1, y: 1 } : { x: 1, y: 6 },
			color: "dark",
			image: "pd.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "darkPawn3",
			type: "pawn",
			position: darkOnTop ? { x: 2, y: 1 } : { x: 2, y: 6 },
			color: "dark",
			image: "pd.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "darkPawn4",
			type: "pawn",
			position: darkOnTop ? { x: 3, y: 1 } : { x: 3, y: 6 },
			color: "dark",
			image: "pd.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "darkPawn5",
			type: "pawn",
			position: darkOnTop ? { x: 4, y: 1 } : { x: 4, y: 6 },
			color: "dark",
			image: "pd.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "darkPawn6",
			type: "pawn",
			position: darkOnTop ? { x: 5, y: 1 } : { x: 5, y: 6 },
			color: "dark",
			image: "pd.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "darkPawn7",
			type: "pawn",
			position: darkOnTop ? { x: 6, y: 1 } : { x: 6, y: 6 },
			color: "dark",
			image: "pd.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "darkPawn8",
			type: "pawn",
			position: darkOnTop ? { x: 7, y: 1 } : { x: 7, y: 6 },
			color: "dark",
			image: "pd.png",
			movements: [],
			hasMoved: false,
		},
	];

	const lightPieces = [
		{
			name: "lightRook1",
			type: "rook",
			position: darkOnTop ? { x: 0, y: 7 } : { x: 0, y: 0 },
			color: "light",
			image: "rl.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "lightKnight1",
			type: "knight",
			position: darkOnTop ? { x: 1, y: 7 } : { x: 1, y: 0 },
			color: "light",
			image: "nl.png",
			movements: [],
		},
		{
			name: "lightBishop1",
			type: "bishop",
			position: darkOnTop ? { x: 2, y: 7 } : { x: 2, y: 0 },
			color: "light",
			image: "bl.png",
			movements: [],
		},
		{
			name: "lightQueen",
			type: "queen",
			position: darkOnTop ? { x: 3, y: 7 } : { x: 4, y: 0 },
			color: "light",
			image: "ql.png",
			movements: [],
		},
		{
			name: "lightKing",
			type: "king",
			position: darkOnTop ? { x: 4, y: 7 } : { x: 3, y: 0 },
			color: "light",
			image: "kl.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "lightBishop2",
			type: "bishop",
			position: darkOnTop ? { x: 5, y: 7 } : { x: 5, y: 0 },
			color: "light",
			image: "bl.png",
			movements: [],
		},
		{
			name: "lightKnight2",
			type: "knight",
			position: darkOnTop ? { x: 6, y: 7 } : { x: 6, y: 0 },
			color: "light",
			image: "nl.png",
			movements: [],
		},
		{
			name: "lightRook2",
			type: "rook",
			position: darkOnTop ? { x: 7, y: 7 } : { x: 7, y: 0 },
			color: "light",
			image: "rl.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "lightPawn1",
			type: "pawn",
			position: darkOnTop ? { x: 0, y: 6 } : { x: 0, y: 1 },
			color: "light",
			image: "pl.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "lightPawn2",
			type: "pawn",
			position: darkOnTop ? { x: 1, y: 6 } : { x: 1, y: 1 },
			color: "light",
			image: "pl.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "lightPawn3",
			type: "pawn",
			position: darkOnTop ? { x: 2, y: 6 } : { x: 2, y: 1 },
			color: "light",
			image: "pl.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "lightPawn4",
			type: "pawn",
			position: darkOnTop ? { x: 3, y: 6 } : { x: 3, y: 1 },
			color: "light",
			image: "pl.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "lightPawn5",
			type: "pawn",
			position: darkOnTop ? { x: 4, y: 6 } : { x: 4, y: 1 },
			color: "light",
			image: "pl.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "lightPawn6",
			type: "pawn",
			position: darkOnTop ? { x: 5, y: 6 } : { x: 5, y: 1 },
			color: "light",
			image: "pl.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "lightPawn7",
			type: "pawn",
			position: darkOnTop ? { x: 6, y: 6 } : { x: 6, y: 1 },
			color: "light",
			image: "pl.png",
			movements: [],
			hasMoved: false,
		},
		{
			name: "lightPawn8",
			type: "pawn",
			position: darkOnTop ? { x: 7, y: 6 } : { x: 7, y: 1 },
			color: "light",
			image: "pl.png",
			movements: [],
			hasMoved: false,
		},
	];

	return [...darkPieces, ...lightPieces];
};

export { defineInitialPositions, testHistory, testPieces };
